### PR TITLE
Minor correction to Swift 2.3

### PR DESCRIPTION
**Pull request by huguesbr**
`Swift 2.3` support branch.
Please not it need also to be use with the `Swift 2.3` branch of `InkKit`. As this branch is not merge yet and you can't specify a git/branch in a `podspec`, you need to manually override it in your `Podfile`...

```
  pod 'InkKit', :git => 'https://github.com/huguesbr/InkKit.git', :branch => 'swift-2.3'
  pod 'Peek', :git => 'https://github.com/huguesbr/Peek.git', :branch => 'swift-2.3'
```

Also, same issue that for `InkKit`, can't find a way to set base branch of the fork as it's not a branch but a tag... See this compare for the correct changes: https://github.com/shaps80/Peek/compare/2.2.0...huguesbr:swift-2.3

### CODE REVIEW

**Comment by shaps80** [comment]
Nice one -- I'll take a proper look at this later in the week and try and get it merged in ASAP :)

Thanks for this.

**Comment by huguesbr** [comment]
@shaps80 awesome. Let me know if I can do something when you check.

**Comment by huguesbr** [comment]
don't forget that this PR should not be merge on `master` but on `2.2.0`...

**Comment by shaps80** [comment]
Yep I understand :-)

Shaps

**Comment by huguesbr** [comment]
;) better safe than sorry ¯\_(ツ)_/¯ thx

**Comment by huguesbr** [comment]
@shaps80 congrats for your baby, let me know if you can review this.. ++

**Comment by shaps80** [comment]
Apologies I had forgotten. Yes I can review just need to run it through some testing first. 

Thanks for the contribution. 

Shaps

**Comment by huguesbr** [comment]
@shaps80 cool. keep me posted...

**Comment by huguesbr** [comment]
👍🎅

**Pull request merged**
