### PR TITLE
Add static libs support

### PR DESCRIPTION
**Pull request by mackoj**

### CODE REVIEW

**Comment by shaps80** [comment]
Can you explain reasoning for this? Dynamic Frameworks are supported from iOS 8+ and this lib only supports iOS 9+ so I don't feel this is necessary unless you have some decent reasoning?

Happy to discuss.

**Comment by shaps80** [comment]
Also no PRs will be accepted into master. Please update the PR to point to release/5.1.0

**Comment by mackoj** [comment]
Ok, In order to improve our startup time, we are trying to move every dependency into a lot of static libraries and then build around one dynamic library.

This is the explanation of our journey if you are interested if not we research how to do it without a lot of success until Cocoapods propose this feature.

We started by watching this [WWDC video session](https://developer.apple.com/videos/play/wwdc2016/406/) and read [this article](https://useyourloaf.com/blog/slow-app-startup-times/).
 
We want to achieve something like [Automatic](https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea) or [Artsy/Eigen](https://github.com/artsy/eigen/pull/2561) did.

In order to passe all of our dependency into static dependency, we tried [Amimono](https://github.com/Ruenzuo/cocoapods-amimono), [Accelerator](https://github.com/johnno1962/Accelerator) and [Swift-Staticlibs](https://github.com/keith/swift-staticlibs) but it wasn't a great success.

When Cocoapod [announce that they will support swift static framework](http://blog.cocoapods.org/CocoaPods-1.4.0/#static-frameworks) it's was a great news for us.

The first part of this support came in [1.4.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0) and a second part will come into [1.5.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0.beta.1).

Now some big library is thinking about it like [RXSwift](https://github.com/ReactiveX/RxSwift/pull/1601).

Thanks for your time and library

**Comment by shaps80** [comment]
I had a feeling you might be thinking about pre-main launch times. I've looked into this as well and am completely aware of your situation. 

I need to test this a little more to make sure it doesn't break for anyone else and I'm also not sure if this would be the preferred solution for most people.

I'll leave this open for now and get back to you. I really appreciate you taking the time to state your reasons and thank you for updating the base branch.

Worse case scenario I could probably provide a static lib pod spec variant so you and anyone else who'd prefer that would have access to it where required. I'll look into other options to determine the best course of action.

Cheers.

**Comment by mackoj** [comment]
Thanks for your time @shaps80 have a great day

**Comment by shaps80** [comment]
I've decided to include a secondary pod spec which will be published along with `v5.1.0`.

I'm closing this PR for now, as I've added it to that release and will ensure it is automated along with the release.

**Comment by mackoj** [comment]
Thanks

**Comment by shaps80** [comment]
Hey @mackoj apologies but after some further investigation I’ve found that static library support isn’t possible due to the way Peek works. 

It compiles but crashes at runtime. Ill investigate further in the future but I’m not able to release this just yet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mackoj** [comment]
Thank You for your stewardship.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
