### PR TITLE
Segment renamed to CustomSegment for solving naming conflict

### PR DESCRIPTION
**Pull request by Lukaz32**
# Base Branch

Make sure you're currently pointing to the next release base branch. For example:

`branch: release/5.1.0`

If you're unsure, check the latest tag, it'll be a semantic version higher than that.

# SwiftLint 

Ensure SwiftLint hasn't reported any issues. Code styles must be adhered to.

# README

Does the README need updating? Ensure anything relevant is updated there as well.

### CODE REVIEW

**Comment by shaps80** [comment]
Can you elaborate what the issue is here? I'm not sure where the conflict is arising?
Also, not sure about the name CustomSegment.

**Comment by Lukaz32** [comment]
There seems to be conflict with Apple's own `UISegmentControl.Segment`:

screen shot 2018-07-30 at 14 46 55

screen shot 2018-07-30 at 14 51 37

Do you have any suggestions for a better naming?

**Comment by shaps80** [comment]
Oh interesting. I hadn’t seen that yet. Thanks for posting a screenshot. 

Ok so what about `SegmentDescriptor` or `SegmentItem` or `SegmentElement`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lukaz32** [comment]
SegmentItem seems much more suitable. :)

**Pull request merged**
